# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Meta data
title: 'Klimop: onafhankelijke Freinetbasisschool Oostkamp'
author: ''
description: 'Klimop is een onafhankelijke en pluralistische freinetschool. We bieden kinderen iets moois aan op een minder gebruikelijke manier! En dit met klassen in een prachtig Kasteel op een uniek Kasteeldomein van 4 ha in Oostkamp'

# Site navigation
navigation:
  - title: styleguide
    url: styleguide/
  - title: grid
    url: grid/

# Jekyll settings
permalink: pretty

# Exclude these files from the build process
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
